export const buttonDimensions = {
  default: {
    buttonHeight: '40px',
    buttonWidth: 'auto',
    borderRadius: '8px',
    paddingInline: '16px',
    buttonFontSize: '16px',
    lineHeight: '24px',
    iconHeight: '20px',
    spinnerSize: 'small' as const,
  },
  medium: {
    buttonHeight: '36px',
    buttonWidth: 'auto',
    borderRadius: '6px',
    paddingInline: '14px',
    buttonFontSize: '14px',
    lineHeight: '20px',
    iconHeight: '18px',
    spinnerSize: 'small' as const,
  },
  small: {
    buttonHeight: '32px',
    buttonWidth: 'auto',
    borderRadius: '4px',
    paddingInline: '12px',
    buttonFontSize: '14px',
    lineHeight: '20px',
    iconHeight: '16px',
    spinnerSize: 'small' as const,
  },
  fullWidth: {
    buttonHeight: '40px',
    buttonWidth: '100%',
    borderRadius: '8px',
    paddingInline: '16px',
    buttonFontSize: '16px',
    lineHeight: '24px',
    iconHeight: '20px',
    spinnerSize: 'small' as const,
  },
} as const
